config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# new route to list the tasks
  get "tasks", to: "tasks#index", as: :tasks

  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"

  get "tasks/:id", to: "tasks#show", as: :task

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: :destroy_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <% unless f.object.new_record? %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form', task: @task %>


<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks </h1>

<% @tasks.each do |task| %>
  <% if task.completed == true %>
    <p><input type="checkbox" name="choix" checked="" /><%= link_to "#{task.title}", task_path(task) %>
      <%= link_to ('<i class="fa fa-trash" aria-hidden="true"></i>').html_safe, destroy_task_path(task), method: :delete,
      data: { confirm: "Are you sure?" } %>
      </p>
  <% else %>
    <p><input type="checkbox" name="choix"/><%= link_to "#{task.title}", task_path(task) %><%= link_to ('<i class="fa fa-trash" aria-hidden="true"></i>').html_safe, destroy_task_path(task), method: :delete,
      data: { confirm: "Are you sure?" } %></p>
  <% end %>
<% end %>

  <%= link_to "+ Add a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<!-- <form action="/tasks">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <p>Title</p>
  <input type="text" name="Title">
  <p>Details</p>
  <input type="text" name="Details"><br>
  <button>Create Task</button>
</form>
 -->



<%= render 'form', task: @task %>
<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<% if @task.completed == true %>
 <p><input type="checkbox" name="choix" checked="" />This task is not completed yet</p>
<% else %>
 <p><input type="checkbox" name="choix"/>This task is not completed yet</p>
 <%end  %>

<%= link_to "Back to list", tasks_path %>
<%= link_to "Edit a new task", edit_task_path %>